version: '3'

services:
  db:
    image: binakot/postgresql-postgis-timescaledb
    environment:
      POSTGRES_PASSWORD: test123
  web:
    build: .
    command: python3 src/MyDjangoProject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db