version: '3'

services:
  db:
    image: binakot/postgresql-postgis-timescaledb
    ports:
      - "5432"
    env_file:  
      - config/db/db_env
    volumes:
      - db-data:/pgdata
    networks:
      - db_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network
  web:
    build: .
    command: bash -c "python src/MyDjangoProject/manage.py makemigrations && python src/MyDjangoProject/manage.py migrate && gunicorn src/MyDjangoProject.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network
      

networks:
  nginx_network:
     driver: bridge
  db_network:
     driver: bridge

volumes:
  db-data:
