version: '3'

services:
  db:
    image: binakot/postgresql-postgis-timescaledb
    ports:
      - "5432"
    volumes:
      - db-data:/pgdata
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  web:
    image: jessesongok/docker_django_app_web
    command: python3 src/MyDjangoProject/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-data:
